ikenom/vendor-frontend

src/components/atoms/textWithDivider/index.tsx
src/components/layouts/basic/index.css
src/components/layouts/basic/index.tsx
src/components/molecules/headers/OrderHeader/HeaderActions/index.css
src/components/molecules/headers/OrderHeader/HeaderActions/index.tsx
src/components/molecules/headers/OrderHeader/HeaderContent/index.tsx
src/components/molecules/headers/OrderHeader/HeaderLabel/index.tsx
src/components/molecules/headers/OrderHeader/HeaderNav/index.css
src/components/molecules/headers/OrderHeader/HeaderNav/index.tsx
src/components/molecules/headers/OrderHeader/index.tsx
src/defaultTheme.tsx
src/icons/components/index.tsx
src/icons/svg/moreOptionsIcon.svg
stories/atoms/button.stories.tsx
stories/atoms/textWithBarProps.stories.tsx
stories/icons/icon.stories.tsx
stories/molecules/headNav.stories.tsx
stories/molecules/headerActions.stories.tsx
stories/molecules/headerContent.stories.tsx
stories/molecules/headerLabel.stories.tsx
stories/molecules/orderHeader.stories.tsx

Adding Individual Order Page header molecule

---

src/components/atoms/lineItem/notes/index.tsx
stories/atoms/lineItem/lineItemNotes.stories.tsx

Adding line item note atom with storybook stories

---

src/components/atoms/lineItem/notes/index.css
src/components/molecules/itemDropDown/index.tsx
src/components/molecules/lineItem/lineItemCollapse/index.css
src/components/molecules/lineItem/lineItemCollapse/index.tsx
stories/molecules/lineItem/lineItemCollapse.stories.tsx

https://user-images.githubusercontent.com/40375385/111021231-eb3f6480-8398-11eb-90c5-6cdbce536a75.mov

Adding line item collapse molecule

---

src/components/molecules/lineItem/lineItemSummary/index.tsx
stories/molecules/lineItem/lineItemSummary.stories.tsx

adding line item summary molecule

---

src/components/atoms/lineItem/notes/index.tsx
src/components/molecules/lineItem/lineItemCollapse/index.css
src/components/molecules/lineItem/lineItemCollapse/index.tsx
src/components/molecules/lineItem/lineItemContent/index.tsx
src/components/molecules/lineItem/lineItemSummary/index.tsx
stories/molecules/lineItem/lineItemCollapse.stories.tsx
stories/molecules/lineItem/lineItemContent.stories.tsx

https://user-images.githubusercontent.com/40375385/111042261-8a507480-840a-11eb-8ec5-0b15a051e997.mov

Adding line item content molecule

---

src/components/atoms/lineItem/header/index.tsx
stories/atoms/lineItem/lineItemHeader.stories.tsx

Adding line item header

---

src/components/molecules/modals/modal/index.tsx
src/components/molecules/modals/needsAction/index.tsx
src/icons/components/index.tsx
stories/icons/icon.stories.tsx
stories/molecules/modal/modal.stories.tsx

https://user-images.githubusercontent.com/40375385/111409452-5779db00-86ad-11eb-8bfa-5cddfb62ac94.mov

Needs action modal (css not optimized :( )

---

src/components/molecules/headers/OrderHeader/HeaderActions/index.tsx
src/components/molecules/modals/modal/index.tsx
src/components/molecules/modals/needsAction/index.tsx
src/defaultTheme.tsx
stories/icons/icon.stories.tsx

Rough styles for needs action modal:

Adding needs action modal

---

src/components/atoms/textWithDivider/index.tsx
src/components/atoms/timeDisplay/index.tsx
src/components/molecules/headers/OrderHeader/HeaderLabel/index.tsx
src/components/molecules/modalTimeEdit/index.tsx
src/components/molecules/modals/needsAction/index.tsx
src/components/molecules/modals/timeUpdateModal/index.tsx
src/icons/components/index.tsx
stories/atoms/button.stories.tsx
stories/atoms/timeDisplay.stories.tsx
stories/molecules/modal/modal.stories.tsx
stories/molecules/modal/modalTimeEdit.stories.tsx

Rough styles but all functionality there. Tweaking styles in a later PR.

adding send to kitchen modal

---

src/components/molecules/modals/cancelModal/index.tsx
src/components/molecules/modals/modal/index.tsx
stories/molecules/modal/modal.stories.tsx

Last modal!
https://user-images.githubusercontent.com/40375385/112407286-325c1c80-8cec-11eb-873c-67109dd787ee.mov

Adding cancel modal

---

src/api/order_client.ts
src/components/organisms/Tabs/index.tsx
src/pages/app.tsx
src/store/orderStore.tsx

Add Kitchen Data

---

src/api/order_client.ts
src/components/organisms/Tabs/index.tsx
src/pages/app.tsx
src/store/orderStore.tsx

Add History Data

---

src/components/molecules/modals/modal/index.tsx
src/components/molecules/modals/needsAction/index.tsx

https://user-images.githubusercontent.com/40375385/112760436-f0b9c300-8fc4-11eb-8a6d-ac94f42f809e.mov

Making pause and cancel divs clickable in needs action modal

---

src/api/client.ts
src/api/order_client.ts
src/components/organisms/order/index.tsx
src/pages/index.tsx
src/store/orderStore.tsx

Hook up send to kitchen mutation

---

src/components/organisms/order/index.tsx

Hook up mutation for ready

---

src/components/molecules/headers/OrderHeader/HeaderActions/index.tsx

removing phone icon

---

src/components/molecules/headers/OrderHeader/HeaderNav/index.tsx
src/components/molecules/headers/OrderHeader/index.tsx
src/components/organisms/order/index.tsx
src/models/orders.ts

centering ready text and adding history text

---

src/components/atoms/timeDisplay/index.tsx
src/components/molecules/headers/OrderHeader/HeaderLabel/index.tsx
src/components/molecules/modalTimeEdit/index.tsx
src/components/molecules/modals/modal/index.tsx
src/defaultTheme.tsx
src/icons/components/index.tsx
src/icons/svg/minusIcon.svg
src/icons/svg/plusIcon.svg

https://user-images.githubusercontent.com/40375385/113810915-3c910880-9739-11eb-87ae-4cef3980095e.mov

Style updates based on feedback

---

src/components/atoms/textWithDivider/index.tsx
src/components/atoms/timeRemainingLabel/index.tsx
src/components/layouts/order/index.tsx
src/components/molecules/headers/OrdersHeader/index.tsx
src/components/molecules/modalTimeEdit/index.tsx
src/components/molecules/modals/needsAction/index.tsx
src/components/molecules/modals/timeUpdateModal/index.tsx
src/components/molecules/orders/orderSummary/index.tsx
src/components/organisms/order/index.tsx
src/icons/components/index.tsx
src/icons/svg/loaderIcon.svg
src/models/orders.ts
src/store/orderStore.tsx
stories/icons/icon.stories.tsx

https://user-images.githubusercontent.com/40375385/114313629-2d0d1900-9ac5-11eb-84b4-484be73bf2e9.mov

Updating needs action modal and in kitchen modal

---

ios/App/App/capacitor.config.json
src/pages/app.tsx

https://user-images.githubusercontent.com/40375385/115514987-abe71c00-a252-11eb-97fd-c27996a16d0b.mov

Refresh app every 30 seconds

---

src/components/molecules/history/card/index.tsx
src/components/molecules/history/cardList/index.tsx
src/components/molecules/orders/orderSummary/index.tsx
src/components/molecules/orders/orderSummaryList/index.tsx
src/components/organisms/Tabs/index.tsx
src/models/utils/index.tsx
src/store/orderStore.ts
stories/molecules/history/historyCard.stories.tsx

https://user-images.githubusercontent.com/40375385/116832279-5976fb00-ab82-11eb-8b65-6ae8b898e2f9.mov

Updating history view to match figma

---

src/store/orderStore.ts
src/store/userStore.ts

https://user-images.githubusercontent.com/40375385/125218032-ddcab600-e276-11eb-91a8-905122e6941a.mov

Correctly serialize line items

---

src/components/atoms/lineItem/notes/index.tsx
src/components/molecules/lineItem/lineItemCollapse/index.tsx

Fixing text styles and icon style
